{{ config({ "materialized":'table',
 "alias":'USINDSSP2020_LANDING_TRANSFORM',
 "pre_hook": macros_copy_json('USINDSSP2020_LANDING_CP', 'USINDSSP2020/', '.*[a-z0-9]+-[a-z0-9]+-[a-z0-9]+-[a-z0-9]+-[a-z0-9]*$'),
 "schema": 'PUBLIC'
})}}
 
WITH WRK_USINDSSP2020_LANDING_TRANSFORM AS(
SELECT SOURCE_DATA as SOURCE_DATA
,CURRENT_TIMESTAMP(9) AS INSERT_DTS
,CAST(CURRENT_SESSION() AS VARCHAR) AS PROCESS_ID
,CAST('copy_landing_raw_usindssp2020_load' AS VARCHAR) AS PROCESS
,SOURCE_FILE_NAME
,SOURCE_FILE_ROW_NUMBER
FROM {{source('landing_source','USINDSSP2020_LANDING_CP')}}
)
 
SELECT * FROM WRK_USINDSSP2020_LANDING_TRANSFORM